name: Coverage comments

on: [pull_request]

jobs:
  test-and-report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Ruby (2.6)
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6.6
          bundler-cache: true

      - name: Build and test with RSpec
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
          bundle exec rspec

      # - name: Code Coverage Report
      #   uses: romeovs/lcov-reporter-action@v0.2.21
      #   with:
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
      #     lcov-file: ./coverage/lcov.info
      # - name: Simplecov Report
      #   uses: aki77/simplecov-report-action@v1
      #   with:
      #     token: ${{ secrets.GITHUB_TOKEN }}
      # - name: Upload coverage results
      #   uses: actions/upload-artifact@v2
      #   if: always()
      #   with:
      #     name: coverage-report
      #     path: coverage

    coverage:
      runs-on: ubuntu-latest
      steps:
        - uses: 5monkeys/cobertura-action@master
          with:
            path: coverage/coverage.xml
            repo_token: ${{ secrets.GITHUB_TOKEN }}
            minimum_coverage: 30
